apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-logger
  namespace: priority
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-logger
  template:
    metadata:
      labels:
        app: busybox-logger
    spec:
      containers:
      - name: busybox-logger
        image: busybox:1.36.1
        command: ["sh", "-c", "while true; do echo 'Logging...'; sleep 30; done"]
        # NO priorityClassName initially - student must add it
